apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gd33mvcw4-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-71f089f64c.x5rz.p3.openshiftapps.com/rhtap/rhtap-qe:78084408a5c578597d37a6e631a60e9844b56b06@sha256:687ed1eaca5db22639c8d024cefa5c9ff02b5757d239d5f8fe5b011748827adb
          name: container-image
